# Generated by Django 3.2.5 on 2022-04-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='Nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_users.categories'),
        ),
    ]
