# Generated by Django 3.2.5 on 2022-05-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
