# Generated by Django 3.2.5 on 2022-05-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0005_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='author',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='author_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
