# Generated by Django 3.2.5 on 2022-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0010_address_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Қазақстан', max_length=100),
        ),
    ]
