# Generated by Django 3.2.5 on 2022-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0013_auto_20220514_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
