# Generated by Django 3.2.5 on 2022-06-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0014_auto_20220515_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='car_model',
            field=models.CharField(default='uni', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
